#!/bin/bash
# 
# Save apache logs for future processing
# by opal stats scripts

basedir=/share/backup/apache_logs
date=`date +\%Y\%m\%d`

logs=`ls /var/log/httpd/*log-20* 2>/dev/null`
HostName=`hostname`

if [ "$logs" ]; then
    mkdir -p $basedir/$date
fi

#save all archived logs
for i in /var/log/httpd/*log-20*;
do
    if [ -f $i ] ; then
        mv $i $basedir/$date/
        echo "$HostName filesystem action:  Moved apache logs $logs  to
$basedir/$date"
    fi
done

